/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicioconcesionario;

import javax.swing.ButtonGroup;

/**
 *
 * @author alumno2
 */
public class DialogVehiculo extends javax.swing.JDialog {

    public Vehiculo v;
    ButtonGroup bg = new ButtonGroup();
    public static int contadorId = 0;
    /**
     * Creates new form DialogVehiculo
     */
    public DialogVehiculo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        bg.add(isSegundaMano);
        bg.add(isNotSegundaMano);
    }
    
    public DialogVehiculo(java.awt.Frame parent, boolean modal, Vehiculo v) {
        super(parent, modal);
        initComponents();
        bg.add(isSegundaMano);
        bg.add(isNotSegundaMano);
        
        if(v instanceof Coche)
        {
            this.v = v;
            Coche c;
            c = (Coche)this.v;
            marcaCoche.setText(c.getMarca());
            modeloCoche.setText(c.getModelo());
            precioCoche.setText(String.valueOf(c.getPrecio()));
            kilometraje.setText(String.valueOf(c.getKilometraje()));
            if(c.isEsSegunda())
            {
                isSegundaMano.setSelected(true);
            }
            else if (!c.isEsSegunda())
            {
                isNotSegundaMano.setSelected(true);
            }
        }
        if(v instanceof Camion)
        {
            this.v = v;
            Camion c;
            c = (Camion)this.v;
            marcaCamion.setText(c.getMarca());
            modeloCamion.setText(c.getModelo());
            precioCamion.setText(String.valueOf(c.getPrecio()));
            carga.setText(String.valueOf(c.getCarga()));
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablaCrearVehiculo = new javax.swing.JTabbedPane();
        creaCoche = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        botonAceptarCoche = new javax.swing.JButton();
        marcaCoche = new javax.swing.JTextField();
        modeloCoche = new javax.swing.JTextField();
        precioCoche = new javax.swing.JTextField();
        kilometraje = new javax.swing.JTextField();
        isSegundaMano = new javax.swing.JRadioButton();
        isNotSegundaMano = new javax.swing.JRadioButton();
        creaCamion = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        marcaCamion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        modeloCamion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        precioCamion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        carga = new javax.swing.JTextField();
        botonAceptarCamion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Marca");

        jLabel2.setText("Modelo");

        jLabel3.setText("Kilometraje");

        jLabel4.setText("Segunda mano");

        jLabel5.setText("Precio");

        botonAceptarCoche.setText("Aceptar");
        botonAceptarCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarCocheActionPerformed(evt);
            }
        });

        isSegundaMano.setText("Sí");

        isNotSegundaMano.setText("No");

        javax.swing.GroupLayout creaCocheLayout = new javax.swing.GroupLayout(creaCoche);
        creaCoche.setLayout(creaCocheLayout);
        creaCocheLayout.setHorizontalGroup(
            creaCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creaCocheLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(creaCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(creaCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(creaCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(precioCoche, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modeloCoche, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(marcaCoche, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(creaCocheLayout.createSequentialGroup()
                        .addComponent(isSegundaMano)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(creaCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonAceptarCoche)
                            .addComponent(isNotSegundaMano))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        creaCocheLayout.setVerticalGroup(
            creaCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creaCocheLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(creaCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(marcaCoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(creaCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(creaCocheLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(6, 6, 6))
                    .addComponent(modeloCoche, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(creaCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(precioCoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(creaCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(kilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(creaCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(isSegundaMano)
                    .addComponent(isNotSegundaMano))
                .addGap(18, 18, 18)
                .addComponent(botonAceptarCoche)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablaCrearVehiculo.addTab("Coche", creaCoche);

        jLabel6.setText("Marca");

        jLabel7.setText("Modelo");

        jLabel8.setText("Precio");

        jLabel9.setText("Carga");

        botonAceptarCamion.setText("Aceptar");
        botonAceptarCamion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarCamionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout creaCamionLayout = new javax.swing.GroupLayout(creaCamion);
        creaCamion.setLayout(creaCamionLayout);
        creaCamionLayout.setHorizontalGroup(
            creaCamionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creaCamionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(creaCamionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(creaCamionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(marcaCamion, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modeloCamion, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precioCamion, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carga, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, creaCamionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonAceptarCamion)
                .addGap(85, 85, 85))
        );
        creaCamionLayout.setVerticalGroup(
            creaCamionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creaCamionLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(creaCamionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(marcaCamion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(20, 20, 20)
                .addGroup(creaCamionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(modeloCamion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(creaCamionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(precioCamion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(creaCamionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(carga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonAceptarCamion)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        tablaCrearVehiculo.addTab("Camión", creaCamion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tablaCrearVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tablaCrearVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarCocheActionPerformed
        if(!marcaCoche.getText().equals("") &&
               !modeloCoche.getText().equals("") &&
               !precioCoche.getText().equals("") &&
               !kilometraje.getText().equals("") &&
              (isSegundaMano.isSelected() | isNotSegundaMano.isSelected())){
                
            Coche coche = new Coche();
            coche.setMarca(marcaCoche.getText());
            coche.setModelo(modeloCoche.getText());
            coche.setPrecio(Float.valueOf(precioCoche.getText()));
            coche.setKilometraje(Integer.valueOf(kilometraje.getText()));
            if(isSegundaMano.isSelected()){
                coche.setEsSegunda(true);
            }else{
                coche.setEsSegunda(false);
            }
            coche.setId(++contadorId);
          v = coche;
        }
        dispose();
    }//GEN-LAST:event_botonAceptarCocheActionPerformed

    private void botonAceptarCamionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarCamionActionPerformed
        if(!marcaCamion.getText().equals("") &&
            !modeloCamion.getText().equals("") &&
            !precioCamion.getText().equals("") &&
            !carga.getText().equals("")){

            Camion camion = new Camion();
            camion.setMarca(marcaCamion.getText());
            camion.setModelo(modeloCamion.getText());
            camion.setPrecio(Float.valueOf(precioCamion.getText()));
            camion.setCarga(Integer.valueOf(carga.getText()));
            camion.setId(++contadorId);
           v = camion;
        }
        
        dispose();
    }//GEN-LAST:event_botonAceptarCamionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogVehiculo dialog = new DialogVehiculo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptarCamion;
    private javax.swing.JButton botonAceptarCoche;
    private javax.swing.JTextField carga;
    private javax.swing.JPanel creaCamion;
    private javax.swing.JPanel creaCoche;
    private javax.swing.JRadioButton isNotSegundaMano;
    private javax.swing.JRadioButton isSegundaMano;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField kilometraje;
    private javax.swing.JTextField marcaCamion;
    private javax.swing.JTextField marcaCoche;
    private javax.swing.JTextField modeloCamion;
    private javax.swing.JTextField modeloCoche;
    private javax.swing.JTextField precioCamion;
    private javax.swing.JTextField precioCoche;
    private javax.swing.JTabbedPane tablaCrearVehiculo;
    // End of variables declaration//GEN-END:variables
}
